version: "3"
services:
  angular:
    container_name: angular
    build: ./frontend
    depends_on:
      - "spring-boot"
    ports:
      - "4200:4200"
    image: projectf/frontend:frontend
    restart: unless-stopped
    environment:
      API_URL: http://spring-boot:8080/
    networks:
      - docker-spring-angular

  spring-boot:
    container_name: spring-boot
    build: ./backend
    ports:
      - "8080:8080"
    image: projectf/backend:backend
    environment:
      spring.datasource.url: jdbc:h2:mem:testdb
      spring.datasource.username: SEP
      spring.datasource.password: SEP
    restart: unless-stopped
    networks:
      - docker-spring-angular

networks:
  docker-spring-angular:
